[package]
name = "optimization-example"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.13.0"
ndarray = "0.15.6"
ndarray-rand = "0.14.0"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
